@@grammar::ASL
@@whitespace :: /(?:\s|\/\/.*|\/\*[\s\S]*?\*\/)*/

start = {statement}+ ;

arglist = "(" {arg}* ")" ;
arg = /[\w\\.\-\_\"]+\,?/ ;
code_block = "{" {statement}* "}" ;

statement
    = function_stmt
    | function_call
    ;

function_stmt
    = function_name arglist code_block ;

function_call
    = function_name arglist ;

function_name
    = 
    | "DefinitionBlock"
    | "External" 
    | "Name" 
    | "Method" 
    | "Return" 
    | "OperationRegion"
    | "Store"
    | "Device"
    | "Buffer"
    | "Notify"
    | "Field"
    | "Scope"
    ;
