@@grammar :: ASL

######################################################################
#   ASL Code only contains one DefinitionBlock per file              #
######################################################################
start               = function ;
function            = func_call code_block ;


######################################################################
#   The basics of all the code are func_callargs and code_blocks     #
#   Every bit of code is inside ( ... ) and { ... }                  #
######################################################################
func_call           = identifier O_PAREN func_args C_PAREN ;
code_block          = O_BRACE {statement}* C_BRACE ;
func_args           = {arg {(COMMA arg)}*}* ;


######################################################################
#   function args can contain vars, fun calls, complete functions    #
######################################################################
arg                 =
                    func_call
                    | identifier
                    | variable
                    ;

variable    = /"[^"]*"|[^\s(),]+/ ;
identifier  = /[A-Za-z_][A-Za-z0-9_]*/ ; 


######################################################################
#   Statements are code inside the code_blocks                       #
######################################################################
statement       =
                field_statement
                | function 
                | func_call
                ;


######################################################################
#   Field entries for OperationRegion fields                         #
######################################################################
field_statement     = field_item {COMMA field_item}* ;
field_item          = offset_statement | field_declaration ;
offset_statement    = 'Offset' O_PAREN variable C_PAREN ;
field_declaration   = identifier COMMA variable ;


######################################################################
#   TOKENS                                                           #
######################################################################
O_PAREN = '(' ;
C_PAREN = ')' ;
O_BRACE = '{' ;
C_BRACE = '}' ;
COMMA   = ',' ;
