# ASL Names
LeadNameChar                :=	'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '_'
NameChar                    :=	'0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | LeadNameChar
RootChar                    :=	'\\'
NameSeg                     :=	<LeadNameChar NameChar NameChar NameChar> | <LeadNameChar NameChar NameChar> | <LeadNameChar NameChar> | <LeadNameChar>
NameString                  :=	<RootChar NamePath> | <PrefixPath NamePath>
PrefixPath                  :=	Nothing | <'^' PrefixPath>
NamePath                    :=	Nothing | <NameSeg NamePathTail>
NamePathTail                :=	Nothing | <'.' NameSeg NamePathTail>

# ASL Language and Terms
ASLCode                     :=	DefinitionBlockTerm
DefinitionBlockTerm         :=	DefinitionBlock(
                                    AMLFileName,            # String
                                    TableSignature,         # String
                                    ComplianceRevision,     # ByteConst
                                    OEMID,                  # String
                                    TableID,                # String
                                    OEMRevision             # DWordConst
                                ) {TermList}
TermList                    :=	Nothing | <Term TermList>
Term                        :=	Object | Type1Opcode | Type2Opcode
CompilerDirective           :=	IncludeTerm | ExternalTerm
ObjectList                  :=	Nothing | <Object ObjectList>
Object                      :=	CompilerDirective | NamedObject | NameSpaceModifier | UserTerm
DataObject                  :=	BufferTerm | PackageTerm | LiteralData | DataMacros
LiteralData                 :=	Integer | String | ConstTerm
ComputationalData           :=	Integer | String | BufferTerm
DataMacros                  :=	EISAIDTerm | ResourceTemplateTerm
NamedObject                 :=	BankFieldTerm | CreateBitFieldTerm | CreateByteFieldTerm | CreateDWordFieldTerm | CreateFieldTerm | CreateWordFieldTerm | DeviceTerm | EventTerm | FieldTerm | IndexFieldTerm | MethodTerm | MutexTerm | OpRegionTerm | PowerResTerm | ProcessorTerm | ThermalZoneTerm
NameSpaceModifier           :=	AliasTerm | NameTerm | ScopeTerm
UserTerm                    :=	NameString(                 # NameString=>MethodTerm
                                    ArgList
                                ) => DataObject
ArgList                     :=	Nothing | <TermArg ArgListTail>
ArgListTail                 :=	Nothing | <',' TermArg ArgListTail>
TermArg                     :=	Type2Opcode | DataObject | UserTerm | ArgTerm | LocalTerm
Type1Opcode                 :=	BreakTerm | BreakPointTerm | FatalTerm | IfElseTerm | LoadTerm | NoOpTerm | NotifyTerm | ReleaseTerm | ResetTerm | ReturnTerm | SignalTerm | SleepTerm | StallTerm | UnloadTerm | WhileTerm
Type2Opcode                 :=	AcquireTerm | AddTerm | AndTerm | ConcatTerm | CondRefOfTerm | DecTerm | DerefOfTerm | DivideTerm | FindSetLeftBitTerm | FindSetRightBitTerm | FromBCDTerm | IncTerm | IndexTerm | LAndTerm | LEqualTerm | LGreaterTerm | LGreaterEqualTerm | LLessTerm | LLessEqualTerm | LNotTerm | LNotEqualTerm | LOrTerm | MatchTerm | MultiplyTerm | NAndTerm | NOrTerm | NotTerm | ObjectTypeTerm | OrTerm | RefOfTerm | ShiftLeftTerm | ShiftRightTerm | SizeOfTerm | StoreTerm | SubtractTerm | ToBCDTerm | WaitTerm | XorTerm
IncludeTerm                 :=	Include(
                                    IncFilePathName         # String
                                )
ExternalTerm                :=	External(
                                    ObjName,                # NameString
                                    ObjType                 # Nothing | ObjectTypeKeyword
                                )
BankFieldTerm               :=	BankField(
                                    RegionName,             # NameString
                                    BankName,               # NameString
                                    BankValue,              # TermArg=>DWordConst
                                    AccessType,             # AccessTypeKeyword
                                    LockRule,               # LockRuleKeyword
                                    UpdateRule              # UpdateRuleKeyword
                                ) {FieldUnitList}
FieldUnitList               :=	Nothing | <FieldUnit FieldUnitListTail>
FieldUnitListTail           :=	Nothing | <',' FieldUnit FieldUnitListTail>
FieldUnit                   :=	FieldUnitEntry | OffsetTerm | AccessAsTerm
FieldUnitEntry              :=	<Nothing | NameSeg> ',' Integer
OffsetTerm                  :=	Offset(
                                    ByteOffset              # Integer
                                )
AccessAsTerm                :=	AccessAs(
                                    AccessType,             # AccessTypeKeyword
                                    AccessAttribute         # Nothing | ByteConst
                                )
CreateBitFieldTerm          :=	CreateBitField(
                                    SourceBuffer,           # TermArg=>BufferTerm
                                    BitIndex,               # TermArg=>Integer
                                    BitFieldName            # NameString
                                )
CreateByteFieldTerm         :=	CreateByteField(
                                    SourceBuffer,           # TermArg=>BufferTerm
                                    ByteIndex,              # TermArg=>Integer
                                    ByteFieldName           # NameString
                                )
CreateDWordFieldTerm        :=	CreateDWordField(
                                    SourceBuffer,           # TermArg=>BufferTerm
                                    ByteIndex,              # TermArg=>Integer
                                    DWordFieldName          # NameString
                                )
CreateFieldTerm             :=	CreateField(
                                    SourceBuffer,           # TermArg=>BufferTerm
                                    BitIndex,               # TermArg=>Integer
                                    NumBits,                # TermArg=>Integer
                                    FieldName               # NameString
                                )
CreateWordFieldTerm         :=	CreateWordField(
                                    SourceBuffer,           # TermArg=>BufferTerm
                                    ByteIndex,              # TermArg=>Integer
                                    WordFieldName           # NameString
                                )
DeviceTerm                  :=	Device(
                                    DeviceName              # NameString
                                ) {ObjectList}
EventTerm                   :=	Event(
                                    EventName               # NameString
                                )
FieldTerm                   :=	Field(
                                    RegionName,             # NameString
                                    AccessType,             # AccessTypeKeyword
                                    LockRule,               # LockRuleKeyword
                                    UpdateRule              # UpdateRuleKeyword
                                ) {FieldUnitList}
IndexFieldTerm              :=	IndexField(
                                    IndexName,              # NameString
                                    DataName,               # NameString
                                    AccessType,             # AccessTypeKeyword
                                    LockRule,               # LockRuleKeyword
                                    UpdateRule              # UpdateRuleKeyword
                                ) {FieldUnitList}
MethodTerm                  :=	Method(
                                    MethodName,             # NameString
                                    NumArgs,                # Nothing | ByteConst
                                    SerializeRule           # Nothing | SerializeRuleKeyword
                                ) {TermList}
MutexTerm                   :=	Mutex(
                                    MutexName,              # NameString
                                    SyncLevel               # ByteConst
                                )
OpRegionTerm                :=	OperationRegion(
                                    RegionName,             # NameString
                                    RegionSpace,            # RegionSpaceKeyword
                                    Offset,                 # TermArg=>DWordConst
                                    Length                  # TermArg=>DWordConst
                                )
PowerResTerm                :=	PowerResource(
                                    ResourceName,           # NameString
                                    SystemLevel,            # ByteConst
                                    ResourceOrder           # WordConst
                                ) {ObjectList}
ProcessorTerm               :=	Processor(
                                    ProcessorName,          # NameString
                                    ProcessorID,            # ByteConst
                                    PBlockAddress,          # DWordConst
                                    PblockLength            # ByteConst
                                ) {ObjectList}
ThermalZoneTerm             :=	ThermalZone(
                                    ThermalZoneName         # NameString
                                ) {ObjectList}
AliasTerm                   :=	Alias(
                                    SourceObject,           # NameString
                                    AliasObject             # NameString
                                )
NameTerm                    :=	Name(
                                    ObjectName,             # NameString
                                    Object                  # DataObject
                                )
ScopeTerm                   :=	Scope(
                                    Location                # NameString
                                ) {ObjectList}
BreakTerm                   :=	Break
BreakPointTerm              :=	BreakPoint
FatalTerm                   :=	Fatal(
                                    Type,                   # ByteConst
                                    Code,                   # DWordConstF
                                    Arg                     # TermArg=>Integer
                                )
IfElseTerm                  :=	IfTerm ElseTerm
IfTerm                      :=	If(
                                    Predicate               # TermArg=>Integer
                                ) {TermList}
ElseTerm                    :=	Nothing | <Else {TermList}>
LoadTerm                    :=	Load(
                                    Object,                 # NameString
                                    DDBHandle               # SuperName
                                )
NoOpTerm                    :=	Noop
NotifyTerm                  :=	Notify(
                                    Object,                 # SuperName
                                    NotificationValue       # TermArg=>ByteConst
                                )
ReleaseTerm                 :=	Release(
                                    SyncObject              # SuperName
                                )
ResetTerm                   :=	Reset(
                                    SyncObject              # SuperName
                                )
ReturnTerm                  :=	Return(
                                    Arg                     # TermArg=>DataObject
                                )
SignalTerm                  :=	Signal(
                                    SyncObject              # SuperName
                                )
SleepTerm                   :=	Sleep(
                                    MilliSecs               # TermArg=>Integer
                                )
StallTerm                   :=	Stall(
                                    MicroSecs               # TermArg=>Integer
                                )
UnloadTerm                  :=	Unload(
                                    DDBHandle               # SuperName
                                )
WhileTerm                   :=	While(
                                    Predicate               # TermArg=>Integer
                                ) {TermList}
AcquireTerm                 :=	Acquire(
                                    SyncObject,             # SuperName
                                    TimeoutValue            # WordConst
                                ) => Boolean                # Ones means timed-out
AddTerm                     :=	Add(
                                    Addend1,                # TermArg=>Integer
                                    Addend2,                # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
AndTerm                     :=	And(
                                    Source1,                # TermArg=>Integer
                                    Source2,                # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
ConcatTerm                  :=	Concatenate(
                                    Source1,                # TermArg=>ComputationalData
                                    Source2,                # TermArg=>ComputationalData
                                    Result                  # Nothing | SuperName
                                ) => ComputationalData
CondRefOfTerm               :=	CondRefOf(
                                    Source,                 # SuperName
                                    Destination             # SuperName
                                ) => Boolean
DecTerm                     :=	Decrement(
                                    Addend                  # SuperName
                                ) => Integer
DerefOfTerm                 :=	DerefOf(
                                    Source                  # TermArg=>ObjectReference
                                                            # ObjectReference is an object
                                                            # produced by terms such as
                                                            # Index, RefOf or CondRefOf.
                                ) => ObjectReference
DivideTerm                  :=	Divide(
                                    Dividend,               # TermArg=>Integer
                                    Divisor,                # TermArg=>Integer
                                    Remainder,              # Nothing | SuperName
                                    Result                  # Nothing | SuperName
                                ) => Integer                # returns Result
FindSetLeftBitTerm          :=	FindSetLeftBit(
                                    Source,                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
FindSetRightBitTerm         :=	FindSetRightBit(
                                    Source,                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
FromBCDTerm                 :=	FromBCD(
                                    BCDValue,               # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
IncTerm                     :=	Increment(
                                    Addend                  # SuperName
                                ) => Integer
IndexTerm                   :=	Index(
                                    Source,                 # TermArg=><BufferTerm | PackageTerm>
                                    Index,                  # TermArg=>Integer
                                    Destination             # Nothing | SuperName
                                ) => ObjectReference
LAndTerm                    :=	LAnd(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LEqualTerm                  :=	LEqual(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LGreaterTerm                :=	LGreater(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LGreaterEqualTerm           :=	LGreaterEqual(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LLessTerm                   :=	LLess(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LLessEqualTerm              :=	LLessEqual(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LNotTerm                    :=	LNot(
                                    Source,                 # TermArg=>Integer
                                ) => Boolean
LNotEqualTerm               :=	LNotEqual(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
LOrTerm                     :=	LOr(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                ) => Boolean
MatchTerm                   :=	Match(
                                    SearchPackage,          # TermArg=>Package
                                    Op1,                    # MatchOpKeyword
                                    MatchObject1,           # TermArg=>Integer
                                    Op2,                    # MatchOpKeyword
                                    MatchObject2,           # TermArg=>Integer
                                    StartIndex              # TermArg=>Integer
                                ) => Ones | Integer
MultiplyTerm                :=	Multiply(
                                    Multiplicand,           # TermArg=>Integer
                                    Multiplier,             # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
NAndTerm                    :=	NAnd(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
NOrTerm                     :=	NOr(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
NotTerm                     :=	Not(
                                    Source,                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
ObjectTypeTerm              :=	ObjectType(
                                    Object                  # SuperName
                                ) => Integer
OrTerm                      :=	Or(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
RefOfTerm                   :=	RefOf(
                                    Object                  # SuperName
                                ) => ObjectReference
ShiftLeftTerm               :=	ShiftLeft(
                                    Source,                 # TermArg=>Integer
                                    ShiftCount              # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
ShiftRightTerm              :=	ShiftRight(
                                    Source,                 # TermArg=>Integer
                                    ShiftCount              # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
SizeOfTerm                  :=	SizeOf(
                                    DataObject              # SuperName=>DataObject
                                ) => Integer
StoreTerm                   :=	Store(
                                    Source,                 # TermArg=>DataObject
                                    Destination             # SuperName
                                ) => DataObject
SubtractTerm                :=	Subtract(
                                    Addend1,                # TermArg=>Integer
                                    Addend2,                # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
ToBCDTerm                   :=	ToBCD(
                                    Value,                  # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
WaitTerm                    :=	Wait(
                                    SyncObject,             # SuperName
                                    TimeoutValue            # TermArg=>Integer
                                ) => Boolean
XOrTerm                     :=	XOr(
                                    Source1,                # TermArg=>Integer
                                    Source2                 # TermArg=>Integer
                                    Result                  # Nothing | SuperName
                                ) => Integer
ObjectTypeKeyword           :=	UnknownObj | IntObj | StrObj | BuffObj | PkgObj | FieldUnitObj | DeviceObj | EventObj | MethodObj | MutexObj | OpRegionObj | PowerResObj | ThermalZoneObj | BuffFieldObj | DDBHandleObj
AcessTypeKeyword            :=	AnyAcc | ByteAcc | WordAcc | DWordAcc | BlockAcc | SMBSendRecvAcc | SMBQuickAcc
LockRuleKeyword             :=	Lock | NoLock
UpdateRuleKeyword           :=	Preserve | WriteAsOnes | WriteAsZeros
RegionSpaceKeyword          :=	UserDefRegionSpace | SystemIO | SystemMemory | PCI_Config | EmbeddedControl | SMBus
UserDefRegionSpace          :=	0x80-0xff
SerializeRuleKeyword        :=	Serialized | NotSerialized
MatchOpKeyword              :=	MTR | MEQ | MLE | MLT | MGE | MGT
DMATypeKeyword              :=	Compatibility | TypeA | TypeB | TypeF
BusMasterKeyword            :=	BusMaster | NotBusMaster
XferTypeKeyword             :=	Transfer8 | Transfer16 | Transfer8_16
ResourceTypeKeyword         :=	ResourceConsumer | ResourceProducer
MinKeyword                  :=	MinFixed | MinNotFixed
MaxKeyword                  :=	MaxFixed | MaxNotFixed
DecodeKeyword               :=	SubDecode | PosDecode
RangeTypeKeyword            :=	ISAOnlyRanges | NonISAOnlyRanges | EntireRange
MemTypeKeyword              :=	Cacheable | WriteCombining | Prefetchable | NonCacheable
ReadWriteKeyword            :=	ReadWrite | ReadOnly
InterruptTypeKeyword        :=	Edge | Level
InterruptLevel              :=	ActiveHigh | ActiveLow
ShareTypeKeyword            :=	Shared | Exclusive
IODecodeKeyword             :=	Decode16 | Decode10
SuperName                   :=	NameString | ArgTerm | LocalTerm | DebugTerm | IndexTerm
ArgTerm                     :=	Arg0 | Arg1 | Arg2 | Arg3 | Arg4 | Arg5 | Arg6
LocalTerm                   :=	Local0 | Local1 | Local2 | Local3 | Local4 | Local5 | Local6 | Local7
DebugTerm                   :=	Debug
Integer                     :=	ByteConst | WordConst | DWordConst
ByteConst                   :=	0x00-0xff
WordConst                   :=	0x0000-0xffff
DWordConst                  :=	0x00000000-0xffffffff
String                      :=	'"' AsciiCharList '"'
AsciiCharList               :=	Nothing | <AsciiChar AsciiCharList>
AsciiChar                   :=	0x01-0x7f
NullChar                    :=	0x00
ConstTerm                   :=	Zero | One | Ones | Revision
Boolean                     :=	True | False
True                        :=	Ones
False                       :=	Zero
BufferTerm                  :=	Buffer(
                                    BuffSize                # Nothing | TermArg=>Integer
                                ) {String | ByteList}
ByteList                    :=	Nothing | <ByteConst ByteListTail>
ByteListTail                :=	Nothing | <',' ByteConst ByteListTail>
DWordList                   :=	Nothing | <DWordConst DWordListTail>
DWordListTail               :=	Nothing | <',' DWordConst DWordListTail>
PackageTerm                 :=	Package(
                                    NumElements             # Nothing | ByteConst
                                ) {PackageList}
PackageList                 :=	Nothing | <PackageElement PackageListTail>
PackageListTail             :=	Nothing | <',' PackageElement PackageListTail>
PackageElement              :=	DataObject | NameString
EISAIDTerm                  :=	EISAID(
                                    EISAIDString            # String
                                ) => DWordConst
ResourceTemplateTerm        :=	ResourceTemplate() {ResourceMacroList} => BufferTerm
ResourceMacroList           :=	Nothing | <ResourceMacroTerm ResourceMacroList>
ResourceMacroTerm           :=	DMATerm | DWordIOTerm | DWordMemoryTerm | EndDependentFnTerm | FixedIOTerm | InterruptTerm | IOTerm | IRQNoFlagsTerm | IRQTerm | Memory24Term | Memory32FixedTerm | Memory32Term | QWordIOTerm | QWordMemoryTerm | StartDependentFnTerm | StartDependentFnNoPriTerm | VendorLongTerm | VendorShortTerm | WordBusNumberTerm | WordIOTerm
DMATerm                     :=	DMA(
                                    DMAType,                # DMATypeKeyword (_TYP)
                                    BusMaster,              # BusMasterKeyword (_BM)
                                    XferType,               # XferTypeKeyword (_SIZ)
                                    ResourceTag             # Nothing | NameString
                                ) {ByteList}                # List of channels (0-17)
DWordIOTerm                 :=	DWORDIO(
                                    ResourceType,           # Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    MinType,                # Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType,                # Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode,                 # Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType,              # Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity,     # DWordConst (_GRA)
                                    MinAddress,             # DWordConst (_MIN)
                                    MaxAddress,             # DWordConst (_MAX)
                                    Translation,            # DWordConst (_TRA)
                                    AddressLen,             # DWordConst (_LEN)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                )
DWordMemoryTerm             :=	DWORDMemory(
                                    ResourceType,           # Nothing (ResourceConsumer) | ResourceTypeKeyword
                                    Decode,                 # Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType,                # Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType,                # Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    MemType,                # Nothing (NonCacheable) | MemTypeKeyword (_MEM)
                                    ReadWriteType,          # ReadWriteKeyword (_RW)
                                    AddressGranularity,     # DWordConst (_GRA)
                                    MinAddress,             # DWordConst (_MIN)
                                    MaxAddress,             # DWordConst (_MAX)
                                    Translation,            # DWordConst (_TRA)
                                    AddressLen,             # DWordConst (_LEN)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                )
EndDependentFnTerm          :=	EndDependentFn()
FixedIOTerm                 :=	FixedIO(
                                    AddressBase,            # WordConst (_BAS)
                                    RangeLen,               # ByteConst (_LEN)
                                    ResourceTag             # Nothing | NameString
                                )
InterruptTerm               :=	Interrupt(
                                    ResourceType,           # Nothing (ResourceConsumer) | ResourceTypeKeyword
                                    InterruptType,          # InterruptTypeKeyword (_LL, _HE)
                                    InterruptLevel,         # InterruptLevelKeyword (_LL, _HE)
                                    ShareType,              # Nothing (Exclusive) ShareTypeKeyword (_SHR)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                ) {DWordList}               # list of interrupts (_INT)
IOTerm                      :=	IO(
                                    IODecode,               # IODecodeKeyword (_DEC)
                                    MinAddress,             # WordConst (_MIN)
                                    MaxAddress,             # WordConst (_MAX)
                                    Alignment,              # ByteConst (_ALN)
                                    RangeLen,               # ByteConst (_LEN)
                                    ResourceTag             # Nothing | NameString
                                )
IRQNoFlagsTerm              :=	IRQNoFlags(
                                    ResourceTag             # Nothing | NameString
                                ) {ByteList}                # list of interrupts (0-15)
IRQTerm                     :=	IRQ(
                                    InterruptType,          # InterruptTypeKeyword (_LL, _HE)
                                    InterruptLevel,         # InterruptLevelKeyword (_LL, _HE)
                                    ShareType,              # Nothing (Exclusive) ShareTypeKeyword (_SHR)
                                    ResourceTag             # Nothing | NameString
                                ) {ByteList}                # list of interrupts (0-15)
Memory24Term                :=	Memory24(
                                    ReadWriteType,          # ReadWriteKeyword (_RW)
                                    MinAddress[23:8],       # WordConst (_MIN)
                                    MaxAddress[23:8],       # WordConst (_MAX)
                                    Alignment,              # WordConst (_ALN)
                                    RangeLen,               # WordConst (_LEN)
                                    ResourceTag             # Nothing | NameString
                                )
Memory32FixedTerm           :=	Memory32Fixed(
                                    ReadWriteType,          # ReadWriteKeyword (_RW)
                                    AddressBase,            # DWordConst (_BAS)
                                    RangeLen,               # DWordConst (_LEN)
                                    ResourceTag             # Nothing | NameString
                                )
Memory32Term                :=	Memory32(
                                    ReadWriteType,          # ReadWriteKeyword (_RW)
                                    MinAddress,             # DWordConst (_MIN)
                                    MaxAddress,             # DWordConst (_MAX)
                                    Alignment,              # DWordConst (_ALN)
                                    RangeLen,               # DWordConst (_LEN)
                                    ResourceTag             # Nothing | NameString
                                )
QWordIOTerm                 :=	QWORDIO(
                                    ResourceType,           # Nothing (ResourceConsumer) | ResourceTypeKeyword
                                    MinType,                # Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType,                # Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode,                 # Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType,              # Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity,     # QWordConst (_GRA)
                                    MinAddress,             # QWordConst (_MIN)
                                    MaxAddress,             # QWordConst (_MAX)
                                    Translation,            # QWordConst (_TRA)
                                    AddressLen,             # QWordConst (_LEN)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                )
QWordMemoryTerm             :=	QWORDMemory(
                                    ResourceType,           # Nothing (ResourceConsumer) | ResourceTypeKeyword
                                    Decode,                 # Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType,                # Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType,                # Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    MemType,                # Nothing (NonCacheable) | MemTypeKeyword (_MEM)
                                    ReadWriteType,          # ReadWriteKeyword (_RW)
                                    AddressGranularity,     # QWordConst (_GRA)
                                    MinAddress,             # QWordConst (_MIN)
                                    MaxAddress,             # QWordConst (_MAX)
                                    Translation,            # QWordConst (_TRA)
                                    AddressLen,             # QWordConst (_LEN)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                )
StartDependentFnTerm        :=	StartDependentFn(
                                    CompatPriority,         # ByteConst (0-2)
                                    PerfRobustPriority      # ByteConst (0-2)
                                ) {ResourceMacroList}
StartDependentFnNoPriTerm   :=  StartDependentFnNoPri() {ResourceMacroList}
VendorLongTerm              :=	VendorLong(
                                    ResourceTag             # Nothing | NameString
                                ) {ByteList}
VendorShortTerm             :=	VendorShort(
                                    ResourceTag             # Nothing | NameString
                                ) {ByteList}                # up to 7 bytes
WordBusNumberTerm           :=	WordBusNumber(
                                    ResourceType,           # Nothing (ResourceConsumer) | ResourceTypeKeyword
                                    MinType,                # Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType,                # Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode,                 # Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    AddressGranularity,     # WordConst (_GRA)
                                    MinAddress,             # WordConst (_MIN)
                                    MaxAddress,             # WordConst (_MAX)
                                    Translation,            # WordConst (_TRA)
                                    AddressLen,             # WordConst (_LEN)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                )
WordIOTerm                  :=	WordIO(
                                    ResourceType,           # Nothing (ResourceConsumer) | ResourceTypeKeyword
                                    MinType,                # Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType,                # Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode,                 # Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType,              # Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity,     # WordConst (_GRA)
                                    MinAddress,             # WordConst (_MIN)
                                    MaxAddress,             # WordConst (_MAX)
                                    Translation,            # WordConst (_TRA)
                                    AddressLen,             # WordConst (_LEN)
                                    ResSourceIndex,         # Nothing | ByteConst
                                    ResSource,              # Nothing | String
                                    ResourceTag             # Nothing | NameString
                                )