
# 19.2. ASL Language Grammar

## 19.2.2. ASL Name and Pathname Terms

### Name and path characters supported
LeadNameChar                :=	'A'-'Z' | 'a'-'z' | '_'
DigitChar                   :=	'0'-'9'
NameChar                    :=	DigitChar | LeadNameChar
RootChar                    :=	''
ParentPrefixChar            :=	'^'
PathSeparatorChar           :=	'.'
CommaChar                   :=	','
SemicolonDelimiter          :=	Nothing | ';'

### Names and paths
NameSeg                     :=	<LeadNameChar> | <LeadNameChar NameChar> | <LeadNameChar NameChar NameChar> | <LeadNameChar NameChar NameChar NameChar>
NameString                  :=	<RootChar NamePath> | <ParentPrefixChar PrefixPath NamePath> | NonEmptyNamePath
NamePath                    :=	Nothing | <NameSeg NamePathTail>
NamePathTail                :=	Nothing | <PathSeparatorChar NameSeg NamePathTail>
NonEmptyNamePath            :=	NameSeg | <NameSeg NamePathTail>
PrefixPath                  :=	Nothing | <ParentPrefixChar PrefixPath>

## 19.2.3. ASL Root and Secondary Terms

### Root Terms
ASLCode                     :=	DefinitionBlockList
DefinitionBlockList         :=	DefinitionBlockTerm | <DefinitionBlockTerm DefinitionBlockList>

### Major Terms
SuperName                   :=	NameString | ArgTerm | LocalTerm | DebugTerm | ReferenceTypeOpcode | MethodInvocationTerm
Target                      :=	Nothing | SuperName
TermArg                     :=	ExpressionOpcode | DataObject | ArgTerm | LocalTerm | NameString | SymbolicExpression
MethodInvocationTerm        :=	NameString ( // NameString => Method
                                    ArgList
                                ) => Nothing | DataRefObject

### List Terms
ArgList                     :=	Nothing | <TermArg ArgListTail>
ArgListTail                 :=	Nothing | <CommaChar TermArg ArgListTail>
ByteList                    :=	Nothing | <ByteConstExpr ByteListTail>
ByteListTail                :=	Nothing | <CommaChar ByteConstExpr ByteListTail>
DWordList                   :=	Nothing | <DwordConstExpr DwordListTail>
DWordListTail               :=	Nothing | <CommaChar DwordConstExpr DwordListTail>
ExtendedAccessAttribTerm    :=	ExtendedAccessAttribKeyword (
                                    AccessLength //ByteConst
                                )
FieldUnitList               :=	Nothing | <FieldUnit FieldUnitListTail>
FieldUnitListTail           :=	Nothing | <CommaChar FieldUnit FieldUnitListTail>
FieldUnit                   :=	FieldUnitEntry | OffsetTerm | AccessAsTerm | ConnectionTerm
FieldUnitEntry              :=	<Nothing | NameSeg> CommaChar Integer
PackageList                 :=	Nothing | <PackageElement PackageListTail>
PackageListTail             :=	Nothing | <CommaChar PackageElement PackageListTail>
PackageElement              :=	DataObject | NameString
ParameterTypePackage        :=	ObjectTypeKeyword | {Nothing | ParameterTypePackageList}
ParameterTypePackageList    :=	ObjectTypeKeyword | <ObjectTypeKeyword CommaChar ParameterTypePackageList>
ParameterTypesPackage       :=	ObjectTypeKeyword | {Nothing | ParameterTypesPackageList}
ParameterTypesPackageList   :=	ParameterTypePackage | <ParameterTypePackage CommaChar ParameterTypesPackageList>
TermList                    :=	Nothing | <Term SemiColonDelimiter TermList>
Term                        :=	Object | StatementOpcode | ExpressionOpcode | SymbolicExpression
Object                      :=	CompilerDirective | NamedObject | NameSpaceModifier

### Conditional Execution List Terms
CaseTermList                :=	Nothing | CaseTerm | DefaultTerm DefaultTermList | CaseTerm CaseTermList
DefaultTermList             :=	Nothing | CaseTerm | CaseTerm DefaultTermList
IfElseTerm                  :=	IfTerm ElseTerm

## 19.2.4. ASL Data and Constant Terms

### Numeric Value Terms
LeadDigitChar               :=	'1'-'9'
HexDigitChar                :=	DigitChar | 'A'-'F' | 'a'-'f'
OctalDigitChar              :=	'0'-'7'
NullChar                    :=	0x00

### Data Terms
BufferData                  :=	BufferTypeOpcode | BufferTerm
ComputationalData           :=	BufferData | IntegerData | StringData
DataObject                  :=	BufferData | PackageData | IntegerData | StringData
DataRefObject               :=	DataObject | ObjectReference
IntegerData                 :=	IntegerTypeOpcode | Integer | ConstTerm
PackageData                 :=	PackageTerm
StringData                  :=	StringTypeOpcode | String

### Integer Terms
Integer                     :=	DecimalConst | OctalConst | HexConst
DecimalConst                :=	LeadDigitChar | <DecimalConst DigitChar>
OctalConst                  :=	'0' | <OctalConst OctalDigitChar>
HexConst                    :=	<0x HexDigitChar> | <0X HexDigitChar> | <HexConst HexDigitChar>
ByteConst                   :=	Integer => 0x00-0xFF
WordConst                   :=	Integer => 0x0000-0xFFFF
DWordConst                  :=	Integer => 0x00000000-0xFFFFFFFF
QWordConst                  :=	Integer => 0x0000000000000000-0xFFFFFFFFFFFFFFFF
ByteConstExpr               :=	<IntegerTypeOpcode | ConstExprTerm | Integer> => ByteConst
WordConstExpr               :=	<IntegerTypeOpcode | ConstExprTerm | Integer> => WordConst
DWordConstExpr              :=	<IntegerTypeOpcode | ConstExprTerm | Integer> => DWordConst
QWordConstExpr              :=	<IntegerTypeOpcode | ConstExprTerm | Integer> => QWordConst
ConstTerm                   :=	ConstExprTerm | Revision
ConstExprTerm               :=	Zero | One | Ones

### String Terms
String                      :=	''' Utf8CharList '''
Utf8CharList                :=	Nothing | <EscapeSequence Utf8CharList> | <Utf8Char Utf8CharList>
Utf8Char                    :=	0x01-0x21 | 0x23-0x5B | 0x5D-0x7F | 0xC2-0xDF 0x80-0xBF | 0xE0 0xA0-0xBF 0x80-0xBF | 0xE1-0xEC 0x80-0xBF 0x80-0xBF | 0xED 0x80-0x9F 0x80-0xBF | 0xEE-0xEF 0x80-0xBF 0x80-0xBF | 0xF0 0x90-0xBF 0x80-0xBF 0x80-0xBF | 0xF1-0xF3 0x80-0xBF 0x80-0xBF 0x80-0xBF

### Escape sequences
EscapeSequence              :=	SimpleEscapeSequence | OctalEscapeSequence | HexEscapeSequence
HexEscapeSequence           :=	\x HexDigitChar | \x HexDigitChar HexDigitChar
SimpleEscapeSequence        :=	\' | \' | \a | \b | \f | \n | \r | \t | \v | \\'
OctalEscapeSequence         :=	\ OctalDigitChar | \ OctalDigitChar OctalDigitChar | \ OctalDigitChar OctalDigitChar OctalDigitChar

### Miscellaneous Data Type Terms
ObjectReference             :=	Integer
Boolean                     :=	True | False
True                        :=	Ones
False                       :=	Zero

### Symbolic Operator terms
Operators                   :=	'+' | '-' | '*' | '/' | '%' | '&' | '|' | '^' | '~' | '<' | '>' | '!' | '='
CompoundOperators           :=	'<<' | '>>' | '++' | '-' | '==' | '!=' | '<=' | '>=' | '&&' | '||' | '+=' | '-=' | '*=' | '/=' | '%=' | '<<=' | '>>=' | '&=' | '|=' | '^='

## 19.2.5. ASL Opcode Terms
CompilerDirective           :=	IncludeTerm | ExternalTerm
NamedObject                 :=	BankFieldTerm | CreateBitFieldTerm | CreateByteFieldTerm | CreateDWordFieldTerm | CreateFieldTerm | CreateQWordFieldTerm | CreateWordFieldTerm | DataRegionTerm | DeviceTerm | EventTerm | FieldTerm | FunctionTerm | IndexFieldTerm | MethodTerm | MutexTerm | OpRegionTerm | PowerResTerm | ProcessorTerm | ThermalZoneTerm
NameSpaceModifier           :=	AliasTerm | NameTerm | ScopeTerm
SymbolicExpressionTerm      :=	( TermArg ) | AddSymbolicTerm | AndSymbolicTerm | DecSymbolicTerm | DivideSymbolicTerm | IncSymbolicTerm | LAndSymbolicTerm | LEqualSymbolicTerm | LGreaterEqualSymbolicTerm | LGreaterSymbolicTerm | LLessEqualSymbolicTerm | LLessSymbolicTerm | LNotEqualSymbolicTerm | LNotSymbolicTerm | LOrSymbolicTerm | ModSymbolicTerm | MultiplySymbolicTerm | NotSymbolicTerm | OrSymbolicTerm | ShiftLeftSymbolicTerm | ShiftRightSymbolicTerm | SubtractSymbolicTerm | XorSymbolicTerm
SymbolicAssignmentTerm      :=	StoreSymbolicTerm | AddCompoundTerm | AndCompoundTerm | DivideCompoundTerm | ModCompoundTerm | MultiplyCompoundTerm | OrCompoundTerm | ShiftLeftCompoundTerm | ShiftRightCompoundTerm | SubtractCompoundTerm | XorCompoundTerm
StatementOpcode             :=	BreakTerm | BreakPointTerm | ContinueTerm | FatalTerm | ForTerm | IfElseTerm | NoOpTerm | NotifyTerm | ReleaseTerm | ResetTerm | ReturnTerm | SignalTerm | SleepTerm | StallTerm | SwitchTerm | UnloadTerm | WhileTerm
ExpressionOpcode            :=	AcquireTerm | AddTerm | AndTerm | ConcatTerm | ConcatResTerm | CondRefOfTerm | CopyObjectTerm | DecTerm | DerefOfTerm | DivideTerm | FindSetLeftBitTerm | FindSetRightBitTerm | FprintfTerm | FromBCDTerm | IncTerm | IndexTerm | LAndTerm | LEqualTerm | LGreaterTerm | LGreaterEqualTerm | LLessTerm | LLessEqualTerm | LNotTerm | LNotEqualTerm | LOrTerm | MatchTerm | MidTerm | ModTerm | MultiplyTerm | NAndTerm | NOrTerm | NotTerm | ObjectTypeTerm | OrTerm | PrintfTerm | RefOfTerm | ShiftLeftTerm | ShiftRightTerm | SizeOfTerm | StoreTerm | SubtractTerm | TimerTerm | ToBCDTerm | ToBufferTerm | ToDecimalStringTerm | ToHexStringTerm | ToIntegerTerm | ToStringTerm | WaitTerm | XorTerm | MethodInvocationTerm | SymbolicExpressionTerm | SymbolicAssignmentTerm
IntegerTypeOpcode           :=	AddTerm | AndTerm | DecTerm | DerefOfTerm | DivideTerm | EISAIDTerm | FindSetLeftBitTerm | FindSetRightBitTerm | FromBCDTerm | IncTerm | LAndTerm | LEqualTerm | LGreaterTerm | LGreaterEqualTerm | LLessTerm | LLessEqualTerm | LNotTerm | LNotEqualTerm | MatchTerm | ModTerm | MultiplyTerm | NAndTerm | NOrTerm | NotTerm | OrTerm | ShiftLeftTerm | ShiftRightTerm | SubtractTerm | ToBCDTerm | ToIntegerTerm | XorTerm | SymbolicExpressionTerm
StringTypeOpcode            :=	ConcatTerm | DerefOfTerm | FprintfTerm | MidTerm | PrintfTerm | ToDecimalStringTerm | ToHexStringTerm | ToStringTerm
BufferTypeOpcode            :=	ConcatTerm | ConcatResTerm | DerefOfTerm | MidTerm | ResourceTemplateTerm | ToBufferTerm | ToPLDTerm | ToUUIDTerm | UnicodeTerm
ReferenceTypeOpcode         :=	RefOfTerm | DerefOfTerm | IndexTerm | IndexSymbolicTerm | UserTermObj

## 19.2.6. ASL Primary (Terminal) Terms
AccessAsTerm                :=	AccessAs (
                                    AccessType, // AccessTypeKeyword
                                    AccessAttribute // Nothing | ByteConstExpr | AccessAttribKeyword | ExtendedAccessAttribTerm
                                )
AcquireTerm                 :=	Acquire (
                                    SyncObject, // SuperName => Mutex
                                    TimeoutValue // WordConstExpr
                                ) => Boolean // True means the operation timed out and the Mutex was not acquired
AddCompoundTerm             :=	Addend1-Result // TermArg => Integer => Target += Addend2 // TermArg => Integer => Integer
AddSymbolicTerm             :=	Addend1 // TermArg => Integer + Addend2 // TermArg => Integer => Integer
AddTerm                     :=	Add (
                                    Addend1, // TermArg => Integer
                                    Addend2, // TermArg => Integer
                                    Result // Target
                                ) => Integer
AliasTerm                   :=	Alias (
                                    SourceObject, // NameString
                                    AliasObject // NameString
                                )
AndCompoundTerm             :=	Source1-Result // TermArg => Integer => Target
                                &= 
                                Source2 // TermArg => Integer
                                => Integer
AndSymbolicTerm             :=	Source1 // TermArg => Integer
                                &
                                Source2 // TermArg => Integer
                                => Integer
AndTerm                     :=	And (
                                    Source1, // TermArg => Integer
                                    Source2, // TermArg => Integer
                                    Result // Target
                                ) => Integer
ArgTerm                     :=	Arg0 | Arg1 | Arg2 | Arg3 | Arg4 | Arg5 | Arg6
BankFieldTerm               :=	BankField (
                                    RegionName, // NameString => OperationRegion
                                    BankName, // NameString => FieldUnit
                                    BankValue, // TermArg => Integer
                                    AccessType, // AccessTypeKeyword
                                    LockRule, // LockRuleKeyword
                                    UpdateRule // UpdateRuleKeyword
                                ) {FieldUnitList}
BreakPointTerm              :=	BreakPoint
BreakTerm                   :=	Break
BufferTerm                  :=	Buffer (
                                    BuffSize // Nothing | TermArg => Integer
                                ) {StringData | ByteList} => Buffer
CaseTerm                    :=	Case (
                                    Value // DataObject
                                ) {TermList}
ConcatResTerm               :=	ConcatenateResTemplate (
                                    Source1, // TermArg => Buffer
                                    Source2, // TermArg => Buffer
                                    Result // Target
                                ) => Buffer
ConcatTerm                  :=	Concatenate (
                                    Source1, // TermArg => SuperName
                                    Source2, // TermArg => SuperName
                                    Result // Target
                                ) => Buffer | String
ConnectionTerm              :=	Connection (
                                    ConnectionResource // NameString | ResourceMacroTerm
                                )
CondRefOfTerm               :=	CondRefOf (
                                    Source // NameString | ArgTerm | LocalTerm | DerefOfTerm
                                    Destination // Target
                                ) => Boolean
ContinueTerm                :=	Continue
CopyObjectTerm              :=	CopyObject (
                                    Source, // TermArg => DataRefObject
                                    Result, // NameString | LocalTerm | ArgTerm
                                ) => DataRefObject
CreateBitFieldTerm          :=	CreateBitField (
                                    SourceBuffer, // TermArg => Buffer
                                    BitIndex, // TermArg => Integer
                                    BitFieldName // NameString
                                )
CreateByteFieldTerm         :=	CreateByteField (
                                    SourceBuffer, // TermArg => Buffer
                                    ByteIndex, // TermArg => Integer
                                    ByteFieldName // NameString
                                )
CreateDWordFieldTerm        :=	CreateDWordField (
                                    SourceBuffer, // TermArg => Buffer
                                    ByteIndex, // TermArg => Integer
                                    DWordFieldName // NameString
                                )
CreateFieldTerm             :=	CreateField (
                                    SourceBuffer, // TermArg => Buffer
                                    BitIndex, // TermArg => Integer
                                    NumBits, // TermArg => Integer
                                    FieldName // NameString
                                )
CreateQWordFieldTerm        :=	CreateQWordField (
                                    SourceBuffer, // TermArg => Buffer
                                    ByteIndex, // TermArg => Integer
                                    QWordFieldName // NameString
                                )
CreateWordFieldTerm         :=	CreateWordField (
                                    SourceBuffer, // TermArg => Buffer
                                    ByteIndex, // TermArg => Integer
                                    WordFieldName // NameString
                                )
DataRegionTerm              :=	DataTableRegion (
                                    RegionName, // NameString
                                    SignatureString, // TermArg => String
                                    OemIDString, // TermArg => String
                                    OemTableIDString // TermArg => String
                                )
DebugTerm                   :=	Debug
DecSymbolicTerm             :=	Minuend // SuperName => Integer
                                –
                                => Integer
DecTerm                     :=	Decrement (
                                    Minuend // SuperName
                                ) => Integer
DefaultTerm                 :=	Default {TermList}
DefinitionBlockTerm         := | DefinitionBlock (
                                    | AMLFileName, // String 
                                    | TableSignature, // String 
                                    | ComplianceRevision, // ByteConst 
                                    | OEMID, // String 
                                    | TableID, // String 
                                    | OEMRevision // DWordConst 
                                | ) {TermList}
DerefOfTerm                 := | DerefOf (
                                    | Source // NameString
                                    | ArgTerm
                                    | LocalTerm
                                    | RefOfTerm
                                    | CondRefOfTerm
                                    | // IndexTerm
                                    | MethodInvocationTerm
                                | ) => DataRefObject
DeviceTerm                  := | Device (
                                    | DeviceName // NameString 
                                | ) {TermList}
DivideCompoundTerm          := | Dividend-Result // TermArg => Integer => Target | /= | Divisor // TermArg => Integer | => Integer
DivideSymbolicTerm          :=	Dividend // TermArg => Integer
                                /
                                Divisor // TermArg => Integer
                                => Integer
DivideTerm                  :=	Divide (
                                    Dividend, // TermArg => Integer
                                    Divisor, // TermArg => Integer
                                    Remainder, // Target
                                    Result // Target
                                ) => Integer // Returns Result
EISAIDTerm                  :=	EISAID (
                                EisaIdString // StringData
                            ) => DWordConst
ElseIfTerm                  :=	ElseIf (
                                    Predicate // TermArg => Integer
                                ) {TermList} ElseTerm
ElseTerm                    :=	Else {TermList} | ElseIfTerm | Nothing
EventTerm                   :=	Event (
                                    EventName // NameString
                                )
ExternalTerm                :=	External (
                                    ObjName, // NameString
                                    ObjType, // Nothing | ObjectTypeKeyword
                                    ResultType, // Nothing | ParameterTypePackage
                                    ParameterTypes // Nothing | ParameterTypesPackage
                                )
FatalTerm                   :=	Fatal (
                                    Type, // ByteConstExpr
                                    Code, // DWordConstExpr
                                    Arg // TermArg => Integer
                                )
FieldTerm                   :=	Field (
                                    RegionName, // NameString => OperationRegion
                                    AccessType, // AccessTypeKeyword
                                    LockRule, // LockRuleKeyword
                                    UpdateRule // UpdateRuleKeyword
                                ) {FieldUnitList}
FindSetLeftBitTerm          :=	FindSetLeftBit (
                                    Source, // TermArg => Integer
                                    Result // Target
                                ) => Integer
FindSetRightBitTerm         :=	FindSetRightBit (
                                    Source, // TermArg => Integer
                                    Result // Target
                                ) => Integer
ForTerm                     :=	For (
                                    Initialize, // Nothing | TermArg => ComputationalData
                                    Predicate, // Nothing | TermArg => ComputationalData
                                    Update // Nothing | TermArg => ComputationalData
                                ) {TermList}
FprintfTerm                 :=	Fprintf (
                                    TermArg,
                                    String,
                                    PrintfArgList
                                ) => String
FromBCDTerm                 :=	FromBCD (
                                    BCDValue, // TermArg => Integer
                                    Result // Target
                                ) => Integer
FunctionTerm                :=	Function (
                                    FunctionName, // NameString
                                    ReturnType, // Nothing | ParameterTypePackage
                                    ParameterTypes // Nothing | ParameterTypesPackage
                                ) {TermList}
IfTerm                      :=	If (
                                    Predicate // TermArg => Integer
                                ) {TermList}
IncludeTerm                 :=	Include (
                                    FilePathName // StringData
                                )
IncSymbolicTerm             :=	Addend // SuperName => Integer
                                ++
                                => Integer
IncTerm                     :=	Increment (
                                    Addend // SuperName
                                ) => Integer
IndexFieldTerm              :=	IndexField (
                                    IndexName, // NameString => FieldUnit
                                    DataName, // NameString => FieldUnit
                                    AccessType, // AccessTypeKeyword
                                    LockRule, // LockRuleKeyword
                                    UpdateRule // UpdateRuleKeyword
                                ) {FieldUnitList}
IndexSymbolicTerm           :=	Source // TermArg => <string | buffer | packageterm>
                                [Index] // TermArg => Integer
                                => ObjectReference
IndexTerm                   :=	Index (
                                    Source, // TermArg => <string | buffer | packageterm>
                                    Index, // TermArg => Integer
                                    Destination // Target
                                ) => ObjectReference
LAndSymbolicTerm            :=	Source1 // TermArg => Integer
                                &&
                                Source2 // TermArg => Integer
                                => Boolean
LAndTerm                    :=	LAnd (
                                    Source1, // TermArg => Integer
                                    Source2 // TermArg => Integer
                                ) => Boolean
LEqualSymbolicTerm          :=	Source1 // TermArg => ComputationalData
                                ==
                                Source2 // TermArg => ComputationalData
                                => Boolean
LEqualTerm                  :=	LEqual (
                                    Source1, // TermArg => ComputationalData
                                    Source2 // TermArg => ComputationalData
                                ) => Boolean
LGreaterEqualSymbolicTerm   :=	Source1 // TermArg => ComputationalData
                                >=
                                Source2 // TermArg => ComputationalData
                                => Boolean
LGreaterEqualTerm           :=	LGreaterEqual (
                                    Source1, // TermArg => ComputationalData
                                    Source2 // TermArg => ComputationalData
                                ) => Boolean
LGreaterSymbolicTerm        :=	Source1 // TermArg => ComputationalData
                                >
                                Source2 // TermArg => ComputationalData
                                => Boolean
LGreaterTerm                :=	LGreater (
                                    Source1, // TermArg => ComputationalData
                                    Source2 // TermArg => ComputationalData
                                ) => Boolean
LLessEqualSymbolicTerm      :=	Source1 // TermArg => ComputationalData
                                <=
                                Source2 // TermArg => ComputationalData
                                => Boolean
LLessEqualTerm              :=	LLessEqual (
                                    Source1, // TermArg => ComputationalData
                                    Source2 // TermArg => ComputationalData
                                ) => Boolean
LLessSymbolicTerm           :=	Source1 // TermArg => ComputationalData
                                <
                                Source2 // TermArg => ComputationalData
                                => Boolean
LLessTerm                   :=	LLess (
                                    Source1, // TermArg => ComputationalData
                                    Source2 // TermArg => ComputationalData
                                ) => Boolean
LNotEqualTerm               :=	LNotEqual (
                                    Source1, // TermArg => ComputationalData
                                    Source2 // TermArg => ComputationalData
                                ) => Boolean
LNotEqualSymbolicTerm       :=	Source1 // TermArg => ComputationalData
                                !=
                                Source2 // TermArg => ComputationalData
                                => Boolean
LNotSymbolicTerm            :=	!
                                Source // TermArg => Integer
                                => Boolean
LNotTerm                    :=	LNot (
                                    Source, // TermArg => Integer
                                ) => Boolean
LOrSymbolicTerm             :=	Source1 // TermArg => Integer
                                ||
                                Source2 // TermArg => Integer
                                => Boolean
LoadTableTerm               :=	LoadTable (
                                    SignatureString, // TermArg => String
                                    OemIDString, // TermArg => String
                                    OemTableIDString, // TermArg => String
                                    RootPathString, // Nothing | TermArg => String
                                    ParameterPathString, // Nothing | TermArg => String
                                    ParameterData // Nothing | TermArg => DataRefObject
                                ) => Boolean // True (non-zero) means table was successfully loaded
LoadTerm                    :=	Load (
                                    Object, // NameString
                                    Result // SuperName => Boolean - True (non-zero) // means the table was successfully loaded
                                ) => Boolean // True (Ones) means the table was successfully loaded
LocalTerm                   :=	Local0 | Local1 | Local2 | Local3 | Local4 | Local5 | Local6 | Local7
LOrTerm                     :=	LOr (
                                    Source1, // TermArg => Integer
                                    Source2 // TermArg => Integer
                                ) => Boolean
MatchTerm                   :=	Match (
                                    SearchPackage, // TermArg => Package
                                    Op1, // MatchOpKeyword
                                    MatchObject1, // TermArg => ComputationalData
                                    Op2, // MatchOpKeyword
                                    MatchObject2, // TermArg => ComputationalData
                                    StartIndex // TermArg => Integer
                                ) => <ones | integer>
MethodTerm                  :=	Method (
                                    MethodName, // NameString
                                    NumArgs, // Nothing | ByteConstExpr
                                    SerializeRule, // Nothing | SerializeRuleKeyword
                                    SyncLevel, // Nothing | ByteConstExpr
                                    ReturnType, // Nothing | ParameterTypePackage
                                    ParameterTypes // Nothing | ParameterTypesPackage
                                ) {TermList}
MidTerm                     :=	Mid (
                                    Source, // TermArg => <buffer | String>
                                    Index, // TermArg => Integer
                                    Length, // TermArg => Integer
                                    Result // Target
                                ) => <buffer | string>
ModCompoundTerm             :=	Dividend-Result // TermArg => Integer => Target
                                %= 
                                Divisor // TermArg => Integer
                                => Integer
ModSymbolicTerm             :=	Dividend // TermArg => Integer
                                %
                                Divisor // TermArg => Integer
                                => Integer
ModTerm                     :=	Mod (
                                    Dividend, // TermArg => Integer
                                    Divisor, // TermArg => Integer
                                    Result // Target
                                ) => Integer // Returns Result
MultiplyCompoundTerm        :=	Multiplicand-Result // TermArg => Integer => Target
                                *=
                                Multiplier // TermArg => Integer
                                => Integer
MultiplySymbolicTerm        :=	Multiplicand // TermArg => Integer
                                *
                                Multiplier // TermArg => Integer
                                => Integer
MultiplyTerm                :=	Multiply (
                                    Multiplicand, // TermArg => Integer
                                    Multiplier, // TermArg => Integer
                                    Result // Target
                                ) => Integer
MutexTerm                   :=	Mutex (
                                    MutexName, // NameString
                                    SyncLevel // ByteConstExpr
                                )
NameTerm                    :=	Name (
                                    ObjectName, // NameString
                                    Object // DataObject
                                )
NAndTerm                    :=	NAnd (
                                    Source1, // TermArg => Integer
                                    Source2, // TermArg => Integer
                                    Result // Target
                                ) => Integer
NoOpTerm                    :=	NoOp
NOrTerm                     :=	NOr (
                                    Source1, // TermArg => Integer
                                    Source2, // TermArg => Integer
                                    Result // Target
                                ) => Integer
NotifyTerm                  :=	Notify (
                                    Object, // SuperName => <thermalzone | processor | device>
                                    NotificationValue // TermArg => Integer
                                )
NotSymbolicTerm             :=	~
                                Source // TermArg => Integer
                                => Integer
NotTerm                     :=	Not (
                                    Source, // TermArg => Integer
                                    Result // Target
                                ) => Integer
ObjectTypeTerm              :=	ObjectType (
                                    Object // NameString | ArgTerm | LocalTerm | DebugTerm | RefOfTerm | DerefOfTerm | IndexTerm
                                ) => Integer
OffsetTerm                  :=	Offset (
                                    ByteOffset // IntegerData
                                )
OpRegionTerm                :=	OperationRegion (
                                    RegionName, // NameString
                                    RegionSpace, // RegionSpaceKeyword
                                    Offset, // TermArg => Integer
                                    Length // TermArg => Integer
                                )
OrCompoundTerm              :=	Source1-Result // TermArg => Integer => Target
                                |= 
                                Source2 // TermArg => Integer
                                => Integer
OrSymbolicTerm              :=	Source1 // TermArg => Integer
                                |
                                Source2 // TermArg => Integer
                                => Integer
OrTerm                      :=	Or (
                                    Source1, // TermArg => Integer
                                    Source2, // TermArg => Integer
                                    Result // Target
                                ) => Integer
PackageTerm                 :=	Package (
                                    NumElements // Nothing | ByteConstExpr | TermArg => Integer
                                ) {PackageList} => Package
PLDKeyword                  :=	PLD_Revision | PLD_IgnoreColor | PLD_Red | PLD_Green | PLD_Blue | PLD_Width | PLD_Height | PLD_UserVisible | PLD_Dock | PLD_Lid | PLD_Panel | PLD_VerticalPosition | PLD_HorizontalPosition | PLD_Shape | PLD_GroupOrientation | PLD_GroupToken | PLD_GroupPosition | PLD_Bay PLD_Ejectable | PLD_EjectRequired | PLD_CabinetNumber
PLDKeywordList              :=	PLDKeyword = StringDataPLD_Revision | PLDKeyword = IntegerDataPLD_Revision | PLDKeyword = StringDataPLD_Revision, PLDKeywordListPLD_Revision, PLDKeyword = IntegerDataPLD_Revision, PLDKeywordListPLD_Revision
PowerResTerm                :=	PowerResource (
                                    ResourceName, // NameString
                                    SystemLevel, // ByteConstExpr
                                    ResourceOrder // WordConstExpr
                                ) {TermList}
PrintfArgList               :=	TermArg | TermArg , PrintfArgList
PrintfTerm                  :=	Printf (
                                    String,
                                    PrintfArgList
                                ) => String
ProcessorTerm               :=	Processor (
                                    ProcessorName, // NameString
                                    ProcessorID, // ByteConstExpr
                                    PBlockAddress, // DWordConstExpr | Nothing (=0)
                                    PblockLength // ByteConstExpr | Nothing (=0)
                                ) {TermList}
RawDataBufferTerm           :=	RawDataBuffer (
                                    BuffSize // Nothing | WordConst
                                ) { ByteList} => RawDataBuffer
RefOfTerm                   :=	RefOf (
                                    Source // NameString | ArgTerm | LocalTerm | DerefOfTerm
                                ) => ObjectReference
ReleaseTerm                 :=	Release (
                                    SyncObject // SuperName
                                )
ResetTerm                   :=	Reset (
                                    SyncObject // SuperName
                                )
ReturnTerm                  :=	Return (
                                    Arg // Nothing | TermArg => DataRefObject
                                )
ScopeTerm                   :=	Scope (
                                    Location // NameString
                                ) {TermList}
ShiftLeftCompoundTerm       :=	Source-Result // TermArg => Integer => Target
                                <<=
                                ShiftCount // TermArg => Integer
                                => Integer
ShiftLeftSymbolicTerm       :=	Source // TermArg => Integer
                                <<
                                ShiftCount // TermArg => Integer
                                => Integer
ShiftLeftTerm               :=	ShiftLeft (
                                    Source, // TermArg => Integer
                                    ShiftCount, // TermArg => Integer
                                    Result // Target
                                ) => Integer
ShiftRightCompoundTerm      :=	Source-Result // TermArg => Integer => Target
                                >>=
                                ShiftCount // TermArg => Integer
                                => Integer
ShiftRightSymbolicTerm      :=	Source // TermArg => Integer
                                >>
                                ShiftCount // TermArg => Integer
                                => Integer
ShiftRightTerm              :=	ShiftRight (
                                    Source, // TermArg => Integer
                                    ShiftCount, // TermArg => Integer
                                    Result // Target
                                ) => Integer
SignalTerm                  :=	Signal (
                                    SyncObject // SuperName
                                )
SizeOfTerm                  :=	SizeOf (
                                    DataObject // SuperName => <string | buffer | package>
                                ) => Integer
SleepTerm                   :=	Sleep (
                                    MilliSeconds // TermArg => Integer
                                )
StallTerm                   :=	Stall (
                                    MicroSeconds // TermArg => Integer
                                )
StoreSymbolicTerm           :=	Destination // SuperName
                                = 
                                Source // TermArg => DataRefObject
                                => DataRefObject
StoreTerm                   :=	Store (
                                    Source, // TermArg => DataRefObject
                                    Destination // SuperName
                                ) => DataRefObject
SubtractCompoundTerm        :=	Minuend-Result // TermArg => Integer => Target
                                -= 
                                Subtrahend // TermArg => Integer
                                => Integer
SubtractSymbolicTerm        :=	Minuend // TermArg => Integer
                                Subtrahend // TermArg => Integer
                                => Integer
SubtractTerm                :=	Subtract (
                                    Minuend, // TermArg => Integer
                                    Subtrahend, // TermArg => Integer
                                    Result // Target
                                ) => Integer
SwitchTerm                  :=	Switch (
                                    Predicate // TermArg => ComputationalData
                                ) {CaseTermList}
ThermalZoneTerm             :=	ThermalZone (
                                    ThermalZoneName // NameString
                                ) {TermList}
TimerTerm                   :=	Timer => Integer
ToBCDTerm                   :=	ToBCD (
                                    Value, // TermArg => Integer
                                    Result // Target
                                ) => Integer
ToBufferTerm                :=	ToBuffer (
                                    Data, // TermArg => ComputationalData
                                    Result // Target
                                ) => ComputationalData
ToDecimalStringTerm         :=	ToDecimalString (
                                    Data, // TermArg => ComputationalData
                                    Result // Target
                                ) => String
ToHexStringTerm             :=	ToHexString (
                                    Data, // TermArg => ComputationalData
                                    Result // Target
                                ) => String
ToIntegerTerm               :=	ToInteger (
                                    Data, // TermArg => ComputationalData
                                    Result // Target
                                ) => Integer
ToPLDTerm                   :=	ToPLD (
                                    PLDKeywordList
                                ) => Buffer
ToStringTerm                :=	ToString (
                                    Source, // TermArg => Buffer
                                    Length, // Nothing | TermArg => Integer
                                    Result // Target
                                ) => String
ToUUIDTerm                  :=	ToUUID (
                                    String // StringData
                                ) => Buffer
UnicodeTerm                 :=	Unicode (
                                    String // StringData
                                ) => Buffer
UnloadTerm                  :=	Unload (
                                    DDBHandle // SuperName
                                )
WaitTerm                    :=	Wait (
                                    SyncObject, // SuperName => Event
                                    TimeoutValue // TermArg => Integer
                                ) => Boolean // True means timed-out
WhileTerm                   :=	While (
                                    Predicate // TermArg => Integer
                                ) {TermList}
XorCompoundTerm             :=	Source1-Result // TermArg => Integer => Target
                                ^                       = 
                                Source2 // TermArg => Integer
                                => Integer
XorSymbolicTerm             :=	Source1 // TermArg => Integer
                                ^
                                Source2 // TermArg => Integer
                                => Integer
XOrTerm                     :=	XOr (
                                    Source1, // TermArg => Integer
                                    Source2, // TermArg => Integer
                                    Result // Target
                                ) => Integer

## 19.2.7. ASL Parameter Keyword Terms (DONE)
AccessAttribKeyword         :=	AttribQuick | AttribSendReceive | AttribByte | AttribBytes (n) | AttribRawBytes (n) | AttribRawProcessBytes (n) | AttribWord | AttribBlock |AttribProcessCall | AttribBlockProcessCall
AccessTypeKeyword           :=	AnyAcc | ByteAcc | WordAcc | DWordAcc | QWordAcc | BufferAcc
AddressKeyword              :=	AddressRangeMemory | AddressRangeReserved | AddressRangeNVS | AddressRangeACPI
AddressSpaceKeyword         :=	RegionSpaceKeyword | FFixedHW
AddressingModeKeyword       :=	AddressingMode7Bit | AddressingMode10Bit
ByteLengthKeyword           :=	DataBitsFive | DataBitsSix | DataBitsSeven | DataBitsEight | DataBitsNine
BusMasterKeyword            :=	BusMaster | NotBusMaster
ClockPhaseKeyword           :=	ClockPhaseFirst | ClockPhaseSecond
ClockPolarityKeyword        :=	ClockPolarityLow | ClockPolarityHigh
DecodeKeyword               :=	SubDecode | PosDecode
EndianKeyword               :=	BigEndianing | LittleEndian
ExtendedAccessAttribKeyword :=	AttribBytes | AttribRawBytes | AttribRawProcessBytes // Note: Used for GenericSerialBus BufferAcc only.
FlowControlKeyword          :=	FlowControlNone | FlowControlXon | FlowControlHardware
InterruptTypeKeyword        :=	Edge | Level
InterruptLevel              :=	ActiveHigh | ActiveLow
InterruptLevelKeyword       :=	ActiveHigh | ActiveLow | ActiveBoth
IODecodeKeyword             :=	Decode16 | Decode10
IoRestrictionKeyword        :=	IoRestrictionNone | IoRestrictionInputOnly | IoRestrictionOutputOnly | IoRestrictionNoneAndPreserve
LockRuleKeyword             :=	Lock | NoLock
MatchOpKeyword              :=	MTR | MEQ | MLE | MLT | MGE | MGT
MaxKeyword                  :=	MaxFixed | MaxNotFixed
MemTypeKeyword              :=	Cacheable | WriteCombining | Prefetchable | NonCacheable
MinKeyword                  :=	MinFixed | MinNotFixed
ObjectTypeKeyword           :=	UnknownObj | IntObj | StrObj | BuffObj | PkgObj | FieldUnitObj | DeviceObj | EventObj | MethodObj | MutexObj | OpRegionObj | PowerResObj | ThermalZoneObj | BuffFieldObj
ParityKeyword               :=	ParityTypeNone | ParityTypeSpace | ParityTypeMark | ParityTypeOdd | ParityTypeEven
PinConfigKeyword            :=	PullDefault | PullUp | PullDown | PullNone
PolarityKeyword             :=	PolarityHigh | PolarityLow
RangeTypeKeyword            :=	ISAOnlyRanges | NonISAOnlyRanges | EntireRange
ReadWriteKeyword            :=	ReadWrite | ReadOnly
RegionSpaceKeyword          :=	SystemIO | SystemMemory | PCI_Config | EmbeddedControl | SMBus | SystemCMOS | PciBarTarget | IPMI | GeneralPurposeIO | GenericSerialBus | PCC
ResourceTypeKeyword         :=	ResourceConsumer | ResourceProducer
SerializeRuleKeyword        :=	Serialized | NotSerialized
ShareTypeKeyword            :=	Shared | Exclusive | SharedAndWake | ExclusiveAndWake
SlaveModeKeyword            :=	ControllerInitiated | DeviceInitiated
StopBitsKeyword             :=	StopBitsZero | StopBitsOne | StopBitsOnePlusHalf | StopBitsTwo
TransferWidthKeyword        :=	Width8Bit | Width16Bit | Width32Bit | Width64Bit | Width128Bit | Width256Bit
TranslationKeyword          :=	SparseTranslation | DenseTranslation
TypeKeyword                 :=	TypeTranslation | TypeStatic
UpdateRuleKeyword           :=	Preserve | WriteAsOnes | WriteAsZeros
UserDefRegionSpace          :=	IntegerData => 0x80 - 0xFF
XferTypeKeyword             :=	Transfer8 | Transfer16 | Transfer8_16
WireModeKeyword             :=	ThreeWireMode | FourWireMode

## 19.2.8. ASL Resource Template Terms (Only declarated not fully implemented)
ResourceMacroList           :=	Nothing | <resourcemacroterm resourcemacrolist>
ResourceMacroTerm           :=	DMATerm | DWordIOTerm | DWordMemoryTerm | DWordSpaceTerm | EndDependentFnTerm | ExtendedIOTerm | ExtendedMemoryTerm | ExtendedSpaceTerm | FixedDMATerm | FixedIOTerm | GpioIntTerm | GpioIOTerm | I2CSerialBusTerm | InterruptTerm | IOTerm | IRQNoFlagsTerm | IRQTerm | Memory24Term | Memory32FixedTerm | Memory32Term | PinConfigTerm | PinFunctionTerm | PinGroupTerm | PinGroupConfigTerm | PinGroupFunctionTerm | QWordIOTerm | QWordMemoryTerm | QWordSpaceTerm | RegisterTerm | SPISerialBusTerm | StartDependentFnTerm | StartDependentFnNoPriTerm | UARTSerialBusTerm | VendorLongTerm | VendorShortTerm | WordBusNumberTerm | WordIOTerm | WordSpaceTerm
DMATerm                     :=	DMA (
                                    DMAType, // DMATypeKeyword (_TYP)
                                    BusMaster, // BusMasterKeyword (_BM)
                                    XferType, // XferTypeKeyword (_SIZ)
                                    DescriptorName // Nothing | NameString
                                ) {ByteList} // List of channels (0-7 bytes)
DWordIOTerm                 :=	DWordIO (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType, // Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity, // DWordConstExpr (_GRA)
                                    MinAddress, // DWordConstExpr (_MIN)
                                    MaxAddress, // DWordConstExpr (_MAX)
                                    AddressTranslation, // DWordConstExpr (_TRA)
                                    AddressLength, // DWordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName, // Nothing | NameString
                                    TranslationType, // Nothing | TypeKeyword (_TTP)
                                    TranslationDensity // Nothing | TranslationKeyword (_TRS)
                                )
DWordMemoryTerm             :=	DWordMemory (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    MemType, // Nothing (NonCacheable) | MemTypeKeyword (_MEM)
                                    ReadWriteType, // ReadWriteKeyword (_RW)
                                    AddressGranularity, // DWordConstExpr (_GRA)
                                    MinAddress, // DWordConstExpr (_MIN)
                                    MaxAddress, // DWordConstExpr (_MAX)
                                    AddressTranslation, // DWordConstExpr (_TRA)
                                    AddressLength, // DWordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName, // Nothing | NameString
                                    MemoryRangeType, // Nothing | AddressKeyword (_MTP)
                                    TranslationType // Nothing | TypeKeyword (_TTP)
                                )
DWordSpaceTerm              :=	DWordSpace (
                                    ResourceType, // ByteConstExpr (_RT), 0xC0 - 0xFF
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    TypeSpecificFlags, // ByteConstExpr (_TSF)
                                    AddressGranularity, // DWordConstExpr (_GRA)
                                    MinAddress, // DWordConstExpr (_MIN)
                                    MaxAddress, // DWordConstExpr (_MAX)
                                    AddressTranslation, // DWordConstExpr (_TRA)
                                    AddressLength, // DWordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName // Nothing | NameString
                                )
EndDependentFnTerm          :=	EndDependentFn ()
ExtendedIOTerm              :=	ExtendedIO (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType, // Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity, // QWordConstExpr (_GRA)
                                    MinAddress, // QWordConstExpr (_MIN)
                                    MaxAddress, // QWordConstExpr (_MAX)
                                    AddressTranslation, // QWordConstExpr (_TRA)
                                    AddressLength, // QWordConstExpr (_LEN)
                                    TypeSpecificAttributes, // Nothing | QWordConstExpr
                                    DescriptorName, // Nothing | NameString
                                    TranslationType, // Nothing | TypeKeyword (_TTP)
                                    TranslationDensity // Nothing | TranslationKeyword (_TRS)
                                )
ExtendedMemoryTerm          :=	ExtendedMemory (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    MemType, // Nothing (NonCacheable) | MemTypeKeyword (_MEM)
                                    ReadWriteType, // ReadWriteKeyword (_RW)
                                    AddressGranularity, // QWordConstExpr (_GRA)
                                    MinAddress, // QWordConstExpr (_MIN)
                                    MaxAddress, // QWordConstExpr (_MAX)
                                    AddressTranslation, // QWordConstExpr (_TRA)
                                    AddressLength, // QWordConstExpr (_LEN)
                                    TypeSpecificAttributes, // Nothing | QWordConstExpr
                                    DescriptorName, // Nothing | NameString
                                    MemoryRangeType, // Nothing | AddressKeyword (_MTP)
                                    TranslationType // Nothing | TypeKeyword (_TTP)
                                )
ExtendedSpaceTerm           :=	ExtendedSpace (
                                    ResourceType, // ByteConstExpr (_RT), 0xC0 - 0xFF
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    TypeSpecificFlags, // ByteConstExpr (_TSF)
                                    AddressGranularity, // QWordConstExpr (_GRA)
                                    MinAddress, // QWordConstExpr (_MIN)
                                    MaxAddress, // QWordConstExpr (_MAX)
                                    AddressTranslation, // QWordConstExpr (_TRA)
                                    AddressLength, // QWordConstExpr (_LEN)
                                    TypeSpecificAttributes, // Nothing | QWordConstExpr (_ATT)
                                    DescriptorName // Nothing | NameString
                                )
FixedDMATerm                :=	FixedDMA (
                                    DMAReq, // WordConstExpr (_DMA)
                                    Channel, // WordConstExpr (_TYP)
                                    XferWidth, // Nothing (Width32Bit) | TransferWidthKeyword (_SIZ)
                                    DescriptorName, // Nothing | NameString
                                )
FixedIOTerm                 :=	FixedIO (
                                    AddressBase, // WordConstExpr (_BAS)
                                    RangeLength, // ByteConstExpr (_LEN)
                                    DescriptorName // Nothing | NameString
                                )
GpioIntTerm                 :=	GpioInt (
                                    InterruptType, // InterruptTypeKeyword (_MOD)
                                    InterruptLevel, // InterruptLevelKeyword (_POL)
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    PinConfig, // PinConfigKeyword | ByteConstExpr (_PPI)
                                    DeBounceTime // Nothing | WordConstExpr (_DBT)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing (0) | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                ) {DWordList} // List of GPIO pins (_PIN)
GpioIOTerm                  :=	GpioIO (
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    PinConfig, // PinConfigKeyword | ByteConstExpr (_PPIC)
                                    DeBounceTime // Nothing | WordConstExpr (_DBT)
                                    DriveStrength // Nothing | WordConstExpr (_DRS)
                                    IORestriction // Nothing (None) | IORestrictionKeyword (_IOR)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing (0) | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                ) {DWordList} // List of GPIO pins (_PIN)
I2CSerialBusTerm            :=	I2CSerialBusV2 (
                                    SlaveAddress, // WordConstExpr (_ADR)
                                    SlaveMode, // Nothing (ControllerInitiated) | SlaveModeKeyword (_SLV)
                                    ConnectionSpeed, // DWordConstExpr (_SPE)
                                    AddressingMode, // Nothing (AddressingMode7Bit) | AddressModeKeyword (_MOD)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                )
InterruptTerm               :=	Interrupt (
                                    ResourceType, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    InterruptType, // InterruptTypeKeyword (_LL, _HE)
                                    InterruptLevel, // InterruptLevelKeyword (_LL, _HE)
                                    ShareType, // Nothing (Exclusive) ShareTypeKeyword (_SHR)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName // Nothing | NameString
                                ) {DWordList} // list of interrupts (_INT)
IOTerm                      :=	IO (
                                    IODecode, // IODecodeKeyword (_DEC)
                                    MinAddress, // WordConstExpr (_MIN)
                                    MaxAddress, // WordConstExpr (_MAX)
                                    Alignment, // ByteConstExpr (_ALN)
                                    RangeLength, // ByteConstExpr (_LEN)
                                    DescriptorName // Nothing | NameString
                                )
IRQNoFlagsTerm              :=	IRQNoFlags (
                                    DescriptorName // Nothing | NameString
                                ) {ByteList} // list of interrupts (0-15 bytes)
IRQTerm                     :=	IRQ (
                                    InterruptType, // InterruptTypeKeyword (_LL, _HE)
                                    InterruptLevel, // InterruptLevelKeyword (_LL, _HE)
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    DescriptorName // Nothing | NameString
                                ) {ByteList} // list of interrupts (0-15 bytes)
Memory24Term                :=	Memory24 (
                                    ReadWriteType, // ReadWriteKeyword (_RW)
                                    MinAddress[23:8], // WordConstExpr (_MIN)
                                    MaxAddress[23:8], // WordConstExpr (_MAX)
                                    Alignment, // WordConstExpr (_ALN)
                                    RangeLength, // WordConstExpr (_LEN)
                                    DescriptorName // Nothing | NameString
                                )
Memory32FixedTerm           :=	Memory32Fixed (
                                    ReadWriteType, // ReadWriteKeyword (_RW)
                                    AddressBase, // DWordConstExpr (_BAS)
                                    RangeLength, // DWordConstExpr (_LEN)
                                    DescriptorName // Nothing | NameString
                                )
Memory32Term                :=	Memory32 (
                                    ReadWriteType, // ReadWriteKeyword (_RW)
                                    MinAddress, // DWordConstExpr (_MIN)
                                    MaxAddress, // DWordConstExpr (_MAX)
                                    Alignment, // DWordConstExpr (_ALN)
                                    RangeLength, // DWordConstExpr (_LEN)
                                    DescriptorName // Nothing | NameString
                                )
PinConfigTerm               :=	PinConfig (
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    PinConfigType, // ByteData (_TYP)
                                    PinConfigValue, // ByteData (_VAL)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing (0) | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                ) {DWordList} (_PIN)
PinFunctionTerm             :=	PinFunction (
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    PinPullConfiguration, // PinConfigKeyword | ByteConstExpr (_PPI)
                                    FunctionNumber, // WordData
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing (0) | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                ) {DWordList} (_PIN)
PinGroupTerm                :=	PinGroup (
                                    ResourceLabel, // StringData
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                ) {DWordList} (_PIN)
PinGroupConfigTerm          :=	PinGroupConfig (
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    PinConfigType, // ByteData (_TYP)
                                    PinConfigValue, // ByteData (_VAL)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing (0) | ByteConstExpr
                                    ResourceSourceLabel, // StringData
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                )
PinGroupFunctionTerm        :=	PinGroupFunction (
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    FunctionNumber, // WordData (_FUN)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing (0) | ByteConstExpr
                                    ResourceSourceLabel, // StringData
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                )
QWordIOTerm                 :=	QWordIO (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType, // Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity, // QWordConstExpr (_GRA)
                                    MinAddress, // QWordConstExpr (_MIN)
                                    MaxAddress, // QWordConstExpr (_MAX)
                                    AddressTranslation, // QWordConstExpr (_TRA)
                                    AddressLength, // QWordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName, // Nothing | NameString
                                    TranslationType, // Nothing | TypeKeyword (_TTP)
                                    TranslationDensity // Nothing | TranslationKeyword (_TRS)
                                )
QWordMemoryTerm             :=	QWordMemory (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    MemType, // Nothing (NonCacheable) | MemTypeKeyword (_MEM)
                                    ReadWriteType, // ReadWriteKeyword (_RW)
                                    AddressGranularity, // QWordConstExpr (_GRA)
                                    MinAddress, // QWordConstExpr (_MIN)
                                    MaxAddress, // QWordConstExpr (_MAX)
                                    AddressTranslation, // QWordConstExpr (_TRA)
                                    AddressLength, // QWordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName, // Nothing | NameString
                                    MemoryRangeType, // Nothing | AddressKeyword (_MTP)
                                    TranslationType // Nothing | TypeKeyword (_TTP)
                                )
QWordSpaceTerm              :=	QWordSpace (
                                    ResourceType, // ByteConstExpr (_RT), 0xC0 - 0xFF
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    TypeSpecificFlags, // ByteConstExpr (_TSF)
                                    AddressGranularity, // QWordConstExpr (_GRA)
                                    MinAddress, // QWordConstExpr (_MIN)
                                    MaxAddress, // QWordConstExpr (_MAX)
                                    AddressTranslation, // QWordConstExpr (_TRA)
                                    AddressLength, // QWordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName // Nothing | NameString
                                )
RegisterTerm                :=	Register (
                                    AddressSpaceID, // AddressSpaceKeyword (_ASI)
                                    RegisterBitWidth, // ByteConstExpr (_RBW)
                                    RegisterOffset, // ByteConstExpr (_RBO)
                                    RegisterAddress, // QWordConstExpr (_ADR)
                                    AccessSize, // ByteConstExpr (_ASZ)
                                    DescriptorName // Nothing | NameString
                                )
SPISerialBusTerm            :=	SPISerialBusV2 (
                                    DeviceSelection, // WordConstExpr (_ADR)
                                    DeviceSelectionPolarity, // Nothing (PolarityLow) |
                                    DevicePolarityKeyword (_DPL)
                                    WireMode, // Nothing (FourWireMode) | WireModeKeyword (_MOD)
                                    DataBitLength, // ByteConstExpr (_LEN)
                                    SlaveMode, // Nothing (ControllerInitiated) | SlaveModeKeyword (_SLV)
                                    ConnectionSpeed, // DWordConstExpr (_SPE)
                                    ClockPolarity, // ClockPolarityKeyword (_POL)
                                    ClockPhase, // ClockPhaseKeyword (_PHA)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    VendorData // Nothing | RawDataBuffer (_VEN)
                                )
StartDependentFnNoPriTerm   :=	StartDependentFnNoPri () {ResourceMacroList}
StartDependentFnTerm        :=	StartDependentFn (
                                    CompatPriority, // ByteConstExpr (0-2)
                                    PerfRobustPriority // ByteConstExpr (0-2)
                                ) {ResourceMacroList}
UARTSerialBusTerm           :=	UARTSerialBusV2 (
                                    Initial BaudRate, // DwordConstExpr (_SPE)
                                    BitsPerByte, // Nothing (DataBitsEight) | DataBitsKeyword (_LEN)
                                    StopBits, // Nothing (StopBitsOne) | StopBitsKeyword (_STB)
                                    LinesInUse, // ByteConstExpr (_LIN)
                                    IsBigEndian, // Nothing (LittleEndian) | EndianessKeyword (_END)
                                    Parity, // Nothing (ParityTypeNone) | ParityTypeKeyword (_PAR)
                                    FlowControl, // Nothing (FlowControlNone) | FlowControlKeyword (_FLC)
                                    ReceiveBufferSize, // WordConstExpr (_RXL)
                                    TransmitBufferSize, // WordConstExpr (_TXL)
                                    ResourceSource, // StringData
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    DescriptorName, // Nothing | NameString
                                    ShareType, // Nothing (Exclusive) | ShareTypeKeyword (_SHR)
                                    VendorData // Nothing | Object (_VEN)
                                )
VendorLongTerm              :=	VendorLong (
                                    DescriptorName // Nothing | NameString
                                ) {ByteList}
VendorShortTerm             :=	VendorShort (
                                    DescriptorName // Nothing | NameString
                                ) {ByteList} // Up to 7 bytes
WordBusNumberTerm           :=	WordBusNumber (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    AddressGranularity, // WordConstExpr (_GRA)
                                    MinAddress, // WordConstExpr (_MIN)
                                    MaxAddress, // WordConstExpr (_MAX)
                                    AddressTranslation, // WordConstExpr (_TRA)
                                    AddressLength, // WordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName // Nothing | NameString
                                )
WordIOTerm                  :=	WordIO (
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    RangeType, // Nothing (EntireRange) | RangeTypeKeyword (_RNG)
                                    AddressGranularity, // WordConstExpr (_GRA)
                                    MinAddress, // WordConstExpr (_MIN)
                                    MaxAddress, // WordConstExpr (_MAX)
                                    AddressTranslation, // WordConstExpr (_TRA)
                                    AddressLength, // WordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName, // Nothing | NameString
                                    TranslationType, // Nothing | TypeKeyword (_TTP)
                                    TranslationDensity // Nothing | TranslationKeyword (_TRS)
                                )
WordSpaceTerm               :=	WordSpace (
                                    ResourceType, // ByteConstExpr (_RT), 0xC0 - 0xFF
                                    ResourceUsage, // Nothing (ResourceConsumer)| ResourceTypeKeyword
                                    Decode, // Nothing (PosDecode) | DecodeKeyword (_DEC)
                                    MinType, // Nothing (MinNotFixed) | MinKeyword (_MIF)
                                    MaxType, // Nothing (MaxNotFixed) | MaxKeyword (_MAF)
                                    TypeSpecificFlags, // ByteConstExpr (_TSF)
                                    AddressGranularity, // WordConstExpr (_GRA)
                                    MinAddress, // WordConstExpr (_MIN)
                                    MaxAddress, // WordConstExpr (_MAX)
                                    AddressTranslation, // WordConstExpr (_TRA)
                                    AddressLength, // WordConstExpr (_LEN)
                                    ResourceSourceIndex, // Nothing | ByteConstExpr
                                    ResourceSource, // Nothing | StringData
                                    DescriptorName // Nothing | NameString
                                )
